name: 'Get version string'
description: 'Get version string'
inputs:
  version_type:
    description: 'Version type'
    required: true
  major:
    description: 'Major version'
    required: true
  minor:
    description: 'Minor version'
    required: true
  patch:
    description: 'Minor version'
    required: true
  increment:
    description: 'Minor version'
    required: true
outputs:
  version:
    description: 'Version string'
    value: ${{ steps.build-version.outputs.version }}
runs:
  using: "composite"
  steps:
    - name: Build Version Variable
      id: build-version
      shell: bash
      run: |
        if [ "${{ inputs.version_type }}" != "none" ]; then
          echo "version=${{ inputs.major }}.${{ inputs.minor }}.${{ inputs.patch }}" >> $GITHUB_OUTPUT
        else
          echo "version=${{ inputs.major }}.${{ inputs.minor }}.${{ inputs.patch }}-${{ inputs.increment }}"  >> $GITHUB_OUTPUT
        fi