name: build

on:
  push:
    branches: 
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  BLAZEWIND_PROJECT_PATH: ./src/Blazewind/
  WEBSITE_PROJECT_PATH: ./site/Website/
  PACKAGES_PATH: ${{ github.workspace}}/nuget

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
      - name: Restore Blazewind NPM dependencies
        uses: ./.github/actions/restore-npm/
        with:
          path: ${{ env.BLAZEWIND_PROJECT_PATH }}
      - name: Restore Website NPM dependencies
        uses: ./.github/actions/restore-npm/
        with:
          path: ${{ env.WEBSITE_PROJECT_PATH }}
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build -c Release --no-restore /p:ContinuousIntegrationBuild=true
      - name: Run tests
        run: dotnet test --no-build --verbosity normal -c Release /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
      - name: Get version
        id: current-version
        uses: ./.github/actions/current-version/
      - name: Pack package
        working-directory: ${{ env.BLAZEWIND_PROJECT_PATH }}
        run: dotnet pack --no-restore -c Release -o ${{ env.PACKAGES_PATH }} -p:Version=${{ steps.current-version.outputs.version }}
      - name: Publish artifacts
        uses: actions/upload-artifact@v3
        with:
          name: blazewind
          path: ${{ env.PACKAGES_PATH }}
          retention-days: 30
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3